name: Run Supabase Migrations on Deploy

on:
  deployment_status:

jobs:
  run-migrations:
    name: Apply Supabase migrations
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      # Prefer GitHub Secrets, but fall back to repository/environment variables when available.
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN || vars.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF || vars.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD || vars.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link Supabase project
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"

      - name: Run database migrations
        run: supabase db push
